name: Build Element X APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Decode Keystore
        run: |
          echo "${{ secrets.SIGNING_KEYSTORE_BASE64 }}" | base64 -d > app/element-release.jks

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Gplay Release
        run: ./gradlew assembleGplayRelease
        env:
          SIGNING_KEYSTORE_PATH: ${{ github.workspace }}/app/element-release.jks
          SIGNING_KEYSTORE_PASSWORD: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: element-x-gplay-release
          path: app/build/outputs/apk/gplay/release/*.apk
